# API Keys
# GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"
GEMINI_API_KEY='AIzaSyAy6VOGNmLGD4n3P9-y4_9aB0Q85TeVo2s'

VEO_API_KEY = "YOUR_VEO_API_KEY"

# Instagram Credentials
INSTAGRAM_USER_ID = "YOUR_INSTAGRAM_USER_ID"
INSTAGRAM_ACCESS_TOKEN = "YOUR_INSTAGRAM_ACCESS_TOKEN"
CDN_HOSTING_LINK = "YOUR_CDN_HOSTING_LINK"

# Publer API Key
PUBLER_API_KEY = "YOUR_PUBLER_API_KEY"

# Google Cloud Project ID
PROJECT_ID = "YOUR_PROJECT_ID"
