# API Keys
GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"
VEO_API_KEY = "YOUR_VEO_API_KEY"

# Publer API Key
PUBLER_API_KEY = "3bf4ffc2b5e9df030a9cdaa6cbf958854f703f53ca770b69"

# Instagram Credentials
INSTAGRAM_USER_ID = "YOUR_INSTAGRAM_USER_ID"
INSTAGRAM_ACCESS_TOKEN = "YOUR_INSTAGRAM_ACCESS_TOKEN"
CDN_HOSTING_LINK = "YOUR_CDN_HOSTING_LINK"
